### ISSUE TITLE
Received JSON for the providerSettings attribute does not match expected format.

### ISSUE THREAD

**Issue by nvanoost** [montumodi/mongodb-atlas-api-client#16]
**Describe the bug**
I want to change the 'InstanceSizeName' of my cluster, but I get an `Received JSON for the providerSettings attribute does not match expected format.` error back from Mongo.

**To Reproduce**
```
const {user, cluster} = await getClient()
await cluster.updateCluster(clusterName, {
            providerSettings: {
                instanceSizeName: newInstanceSize
            }
        })
            .then( (data) => {
                if(data.error) {
                    result.result = data.detail
                    result.error = true
                } else {
                    result.result = data
                }
            })
            .catch( (reason) => {
                result.result = reason
                result.error = true
            })
```

If I send the data like `'providerSettings.instanceSizeName': 'M40'` I will not get back an error, Mongo will do something ('Creating a plan') but is not resizing the cluster.

I must be wrong at some place but I can't find any example for this...

**Comment by montumodi** [comment]
The correct syntax is `'providerSettings.instanceSizeName': 'M40'` which you are already trying. The job of the atlas client is to send request to mongodb atlas api. If it is stuck on mongo atlas level, may be worth talking to mongo atlas guys. I have used thier chat feature when you login on mongodb atlas very helpful. You will get a reply instantly. Sometimes the deployment gets stuck. It looks like that is the case here.

**Comment by nvanoost** [comment]
Aha clear. Thanks for your reply. I have contacted MongoDB for this!

**Comment by winrono** [comment]
Facing exactly the same issue
`
    const result = await cluster.update(mongo.clusterName, {
        providerSettings: {
            instanceSizeName: 'M20',
        }
    })`

@nvanoost if you managed to find the root cause, could you please share?

**Comment by winrono** [comment]
for those who face the same problem: as per documentation https://docs.atlas.mongodb.com/reference/api/clusters-modify-one/#request-body-parameters it's also mandatory to specify 'providerName' when 'providerSettings' is modified.

So your code will be similar to:
`    const result = await cluster.update(mongo.clusterName, {
        providerSettings: {
            providerName: 'AWS',
            instanceSizeName: 'M20',
        }
    });`
