### ISSUE TITLE
Project ID is a required paramter in configuration

### ISSUE THREAD

**Issue by bencooper222** [montumodi/mongodb-atlas-api-client#17]
**Describe the bug**
The interface `AtlasConfig` requires projectID. My intended use of the API is to create a project and manage the clusters within it so initializing the API client with a projectID doesn't really work. 

Thanks for running this project - I understand it must take a lot of time.

**Comment by montumodi** [comment]
Hi @bencooper222 
Thanks for raising this. Code wise there is no restriction on project id to be mandatory. Typings weren't having project as optional. I have changed this and published a new version. Let me know if it fine now.

**Comment by montumodi** [comment]
Assuming this is no longer an issue, I am closing this.
