### ISSUE TITLE
Create a mongoDB Atlas Search Index

### ISSUE THREAD

**Issue by MattCollins84** [montumodi/mongodb-atlas-api-client#28]
**Is your feature request related to a problem? Please describe.**
I am trying to programmatically create a search index but can't find any way to easily do this.

https://docs.atlas.mongodb.com/reference/atlas-search/tutorial/create-index-api/

**Describe the solution you'd like**
A new method on the cluster object that allows the creation of a search index with all of the defined options

**Describe alternatives you've considered**
I could obviously implement this myself directly, but your module seems like a good fit for something like this :)

**Comment by montumodi** [comment]
Hi @MattCollins84 
I am glad that this package was helpful to you. I have added the support for creating atlas search indexes.

You can find it here - https://www.npmjs.com/package/mongodb-atlas-api-client#atlassearch

The API supported are : https://docs.atlas.mongodb.com/reference/api/atlas-search/

In future, if you need any more entity, feel free to raise a PR and I will be happy to merge.

Thanks,
Ashish

**Comment by MattCollins84** [comment]
Thank you very much
