### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by JamesNSmith** [montumodi/mongodb-atlas-api-client#56]
**Describe the bug**
***The following code:***

```
const {user, cluster} = getClient({
  publicKey,
  privateKey,
  baseUrl,
  projectId,
});

const options = {
  "envelope": true,
  "itemsPerPage": 10,
  "pretty": true,
  "httpOptions": { // This parameter will not be sent as querystring. This will be send to http request package `urllib`
    "timeout": 5000
  }
}

user.getAll(options)

```

***Returns:***

![Screenshot 2024-10-03 at 16 59 15](https://github.com/user-attachments/assets/18fa28d1-8895-47de-8ff2-b950a4aa4577)

***Package Versions:***
"mongodb-atlas-api-client": "4.2.0",
"urllib": "4.2.0"

**Comment by montumodi** [comment]
@JamesNSmith  Let me know if this worked so I can close this isssue.

**Comment by JamesNSmith** [comment]
Hi

The solution works.

Sorry for taking so long to come back.

Regards
James
